// <auto-generated />
namespace MyTunes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IX_GenreName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IX_GenreName));
        
        string IMigrationMetadata.Id
        {
            get { return "201603211604317_IX_GenreName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
